// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package presentity

type AuthPayload struct {
	Token string `json:"token"`
}

type InfoPayload struct {
	Message string `json:"message"`
}
