// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocksecurity

import mock "github.com/stretchr/testify/mock"

// Security is an autogenerated mock type for the ISecurity type
type Security struct {
	mock.Mock
}

// HashPassword provides a mock function with given fields: password, cost
func (_m *Security) HashPassword(password string, cost int) ([]byte, error) {
	ret := _m.Called(password, cost)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string, int) []byte); ok {
		r0 = rf(password, cost)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(password, cost)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyPasswords provides a mock function with given fields: hashedPassword, password
func (_m *Security) VerifyPasswords(hashedPassword string, password string) error {
	ret := _m.Called(hashedPassword, password)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(hashedPassword, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
